const assert=require('node:assert/strict');
const fs=require('node:fs');

const index=fs.readFileSync('index.html','utf8');
const recorder=fs.readFileSync('js/recorder.js','utf8');
const audioRuntime=fs.readFileSync('js/audio-runtime.js','utf8');
const core=fs.readFileSync('js/core.js','utf8');
const appShell=fs.readFileSync('js/app-shell.js','utf8');
const metronome=fs.readFileSync('js/metronome.js','utf8');
const ear=fs.readFileSync('js/ear-trainer.js','utf8');
const rhythm=fs.readFileSync('js/rhythm-trainer.js','utf8');
const jam=fs.readFileSync('js/jam-session.js','utf8');
const cloud=fs.readFileSync('cloud-sync.js','utf8');
const recordingCache=fs.readFileSync('js/recording-cache.js','utf8');
const soundTouchProcessor=fs.readFileSync('vendor/soundtouch/soundtouch-processor.js','utf8');
const soundTouchLicense=fs.readFileSync('vendor/soundtouch/LICENSE','utf8');
const baseMigration=fs.readFileSync('supabase/006_recordings.sql','utf8');
const waveformMigration=fs.readFileSync('supabase/007_recording_waveforms.sql','utf8');
const timestampMigration=fs.readFileSync('supabase/008_recording_timestamps.sql','utf8');
const playbackGainMigration=fs.readFileSync('supabase/009_recording_playback_gain.sql','utf8');
const uploadMigration=fs.readFileSync('supabase/010_recording_uploads.sql','utf8');
const mimeMigration=fs.readFileSync('supabase/011_recording_mime_types.sql','utf8');
const migration=baseMigration+'\n'+waveformMigration+'\n'+timestampMigration+'\n'+playbackGainMigration+'\n'+uploadMigration+'\n'+mimeMigration;
const edge=fs.readFileSync('supabase/functions/delete-account/index.ts','utf8');

assert.match(index,/grid-template-columns:repeat\(3,1fr\)/);
for(const label of ['청음','리듬','트랙']) assert.match(index,new RegExp(`data-mode="[^"]+">${label}<`));
assert.match(index,/id="pane-record"/);
assert.match(index,/id="recordUsage">0 \/ 50</);
assert.match(index,/<details class="card record-history" id="recordListCard" hidden>/);
assert.match(index,/<summary>\s*<span class="record-history-title">목록<\/span>/);
assert.match(index,/id="recordCloudTitle">클라우드 연결 준비 중<\/strong>/);
assert.match(index,/id="recordCloudAction"[^>]*aria-label="계정 연결"/);
assert.match(index,/id="recordCloudAvatar"/);
assert.match(index,/id="recordCloudAvatarFallback"/);
assert.match(index,/id="recordMenuRename"[^>]*>이름 변경</);
assert.match(index,/id="recordMenuDownload"[^>]*>다운로드</);
assert.match(index,/id="recordMenuDelete"[^>]*>삭제</);
assert.doesNotMatch(index,/id="recordMenuCancel"/);
assert.doesNotMatch(index,/id="pane-record"[\s\S]*?<h2>연주 녹음<\/h2>/);
assert.match(index,/id="recordUploadInput"[^>]*accept="\.mp3,[^"]*audio\/mpeg/);
assert.doesNotMatch(index,/id="recordUploadInput"[^>]*accept="[^"]*audio\/\*/);
assert.match(index,/class="record-upload icon" id="recordUpload"[^>]*aria-label="오디오 파일 업로드"/);
assert.doesNotMatch(index,/반주 불러오기/);
assert.match(index,/\.record-list-head\{ margin-bottom:12px; \}/);
assert.match(index,/\.ear-history,\.record-history\{padding:0; overflow:hidden;\}/);
assert.match(index,/\.ear-history > summary,\.record-history > summary\{/);
assert.match(index,/\.record-history-body\{ border-top:1px solid var\(--line-soft\); padding:10px 14px 0; \}/);
assert.match(index,/\.record-upload\{[\s\S]*?background:var\(--signal\); color:var\(--on-signal\)/);
assert.match(index,/#recordListCard\.record-drop-active::after\{ opacity:1; visibility:visible; \}/);
assert.match(index,/id="recordTimer">0:00</);
assert.match(index,/id="recordTimeProgress"[^>]*aria-valuemax="300"[^>]*aria-valuenow="0"/);
assert.match(index,/id="recordState">녹음 준비</);
assert.match(index,/id="recordState">녹음 준비<\/span>[\s\S]*?id="recordToggle"[\s\S]*?id="recordTimeProgress"[\s\S]*?id="recordLevelRow"/);
assert.match(index,/\.record-olive\{[^}]*margin:20px auto 0/);
assert.match(index,/\.record-time-progress\{[^}]*margin:16px auto 0/);
/* 녹음 시간과 올리브 버튼은 좌우로 배치해 세로 공간을 아낀다. */
assert.match(index,/<div class="record-head">[\s\S]*?id="recordTimer"[\s\S]*?id="recordState"[\s\S]*?id="recordToggle"[\s\S]*?<\/div>/);
assert.match(index,/\.record-head\{[^}]*display:flex;[^}]*justify-content:space-between/);
assert.match(index,/\.record-head \.record-olive\{ margin:0/);
assert.match(index,/\.record-stage\{ text-align:center; padding:14px 0 10px; \}/);
assert.match(index,/\.record-level-row\{[^}]*margin:12px auto 8px/);
assert.match(index,/id="recordTimeTrack"/);
assert.match(index,/id="recordTimeFill"/);
assert.doesNotMatch(index,/id="recordTimeMarker"/);
assert.doesNotMatch(index,/id="recordTimeOlive"/);
assert.doesNotMatch(index,/class="record-time-labels"/);
assert.match(index,/\.record-time-progress\{[\s\S]*?width:min\(250px,76%\)/);
assert.match(index,/\.record-time-track\{[\s\S]*?width:100%; height:5px/);
assert.match(index,/\.record-level\{[\s\S]*?height:5px/);
assert.match(index,/\.record-time-fill\{[\s\S]*?background:var\(--signal\)/);
assert.doesNotMatch(index,/\.record-time-marker\{/);
assert.doesNotMatch(index,/\.record-time-olive\{/);
assert.doesNotMatch(index,/@keyframes record-time-olive-roll/);
assert.match(index,/\.record-level-row\{[\s\S]*?width:min\(250px,76%\)/);
assert.match(index,/\.record-meter-icon\{[\s\S]*?width:14px; height:14px/);
assert.match(index,/\.record-level-row\.input-active>\.record-meter-icon\{ stroke:var\(--signal\); \}/);
assert.match(index,/\.record-loop-marker::before\{[\s\S]*?top:-15px;[\s\S]*?font-size:\.6875rem/);
assert.match(index,/\.record-rate-control input\[type="range"\]::\-webkit-slider-thumb\{[\s\S]*?width:14px; height:14px;[\s\S]*?border-radius:50%; background:var\(--signal\)/);

// 튜너·청음과 같은 올리브 기울기, 비율, 씨 위치를 사용한다.
assert.match(index,/\.record-olive-static,\.record-olive\{[\s\S]*?width:76px; height:62\.5px;[\s\S]*?transform:rotate\(-11deg\)/);
assert.match(index,/\.record-olive::after,\.record-olive-static::after\{[\s\S]*?left:calc\(50% \+ 15px\);[\s\S]*?width:23px; height:23px;/);
assert.match(index,/\.record-player-play\{[\s\S]*?transform:rotate\(-11deg\)/);
assert.match(index,/\.record-draft-actions\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
assert.match(index,/\.record-row\{[\s\S]*?min-height:54px;[\s\S]*?grid-template-columns:minmax\(0,1fr\) 44px/);
assert.match(index,/\.record-player-play\{[\s\S]*?width:44px; height:44px;/);
assert.match(index,/\.record-player-play\{[\s\S]*?margin-top:16px/);
assert.match(index,/\.record-player-play::before\{[\s\S]*?width:34px; height:28px;/);
assert.match(index,/\.record-player\{[\s\S]*?min-height:132px;[\s\S]*?grid-template-columns:44px minmax\(0,1fr\); align-items:start/);
assert.match(index,/\.record-player\{[\s\S]*?padding:7px 12px 7px 5px/);
assert.match(index,/\.record-waveform-wrap\{[\s\S]*?height:60px; padding-top:14px/);
assert.match(index,/\.record-waveform\{[\s\S]*?height:44px/);
assert.match(index,/\.record-waveform-svg\{[\s\S]*?inset:2px 0/);
assert.match(index,/\.record-waveform-svg\.played\{[\s\S]*?clip-path:inset/);
assert.match(index,/\.record-waveform\{[\s\S]*?touch-action:pan-y/);
assert.match(index,/\.record-loop-region\{/);
assert.match(index,/\.record-player-tools\{/);

assert.match(recorder,/const MAX_DURATION_MS=5\*60\*1000/);
assert.match(recorder,/const MAX_RECORDINGS=50/);
assert.match(recorder,/recordListCard\.open=true/);
assert.match(recorder,/function formatRecordingDuration\(ms\)/);
assert.match(recorder,/function formatDuration\(ms\)\{[\s\S]*?return Math\.floor\(seconds\/60\)\+':'\+pad\(seconds%60\)/);
assert.match(recorder,/function setRecordingProgress\(ms\)/);
assert.match(recorder,/recordTimeFill\.style\.transform=`scaleX\(\$\{progress\.toFixed\(5\)\}\)`/);
assert.doesNotMatch(recorder,/recordTimeMarker|recordTimeOlive/);
assert.match(recorder,/recordTimer\.textContent=formatRecordingDuration\(ms\)/);
assert.match(recorder,/recordState\.textContent='녹음 준비'/);
assert.match(recorder,/audioBitsPerSecond:96000/);
assert.match(recorder,/echoCancellation:false,noiseSuppression:false,autoGainControl:false/);
assert.match(recorder,/const METRONOME_REFERENCE_RMS=\.1/);
assert.match(recorder,/const PLAYBACK_GAIN_MAX=11\.2/);
assert.match(recorder,/function playbackGainForRecording\(levels,peak\)/);
assert.match(recorder,/METRONOME_REFERENCE_RMS\/Math\.max\(representative,RECORDING_NOISE_FLOOR\)/);
assert.match(recorder,/recordingStream=setupCapture\(ctx\)/);
assert.match(recorder,/recorder=new MediaRecorder\(recordingStream,options\)/);
assert.match(recorder,/channelCountMode='explicit'/);
assert.match(recorder,/function setupCapture\(ctx\)\{[\s\S]*?createMediaStreamDestination\(\)[\s\S]*?return processed/);
assert.match(recorder,/captureDestination=makeMono/);
assert.doesNotMatch(recorder,/Math\.abs\(rowPlaybackGain\(row\)-1\)/);
assert.doesNotMatch(recorder,/updateCaptureNormalization/);
assert.match(recorder,/function meterLevelForRms\(rms\)/);
assert.match(recorder,/const INPUT_ACTIVITY_THRESHOLD=\.001/);
assert.match(recorder,/const INPUT_ACTIVITY_HOLD_MS=180/);
assert.match(recorder,/function clearInputActivity\(\)/);
assert.match(recorder,/recordLevelRow\.classList\.toggle\('input-active'/);
assert.match(recorder,/recordLevelRow\.classList\.remove\('input-active'\)/);
assert.match(recorder,/getFloatTimeDomainData\(data\)/);
assert.match(recorder,/Math\.pow\(normalized,\.78\)/);
assert.doesNotMatch(recorder,/rms\*7/);
assert.match(recorder,/MediaRecorder\.isTypeSupported/);
assert.match(recorder,/function defaultTitle\(\)\{\s*return '무제';/);
assert.match(recorder,/function replaceCloudNativeAudio\(\)/);
assert.match(recorder,/function preferPersistentNativePlayback\(\)\{[\s\S]*?return false;/);
assert.match(recorder,/function confirmPersistentNativeProgress\(/);
assert.match(recorder,/const audio=resetCloudNativeElement\(true\)/);
assert.doesNotMatch(recorder,/cloudNativeAudio\.removeAttribute\('src'\); cloudNativeAudio\.load\(\)/);
assert.match(recorder,/recordedAt=new Date\(\)\.toISOString\(\)/);
assert.match(recorder,/date\.getHours\(\)/);
assert.match(recorder,/recorder\.start\(\);/);
assert.doesNotMatch(recorder,/recorder\.start\(1000\)/);
assert.match(recorder,/registerTransport\(/);
assert.match(recorder,/isPlaying:\(\)=>recording \|\| startPending,[\s\S]*?keepWhenHidden:true/);
assert.match(recorder,/isPlaying:\(\)=>draftIsPlaying\(\) \|\| Boolean\(cloudPlayingId\) \|\| cloudMediaSessionActive,[\s\S]*?keepWhenHidden:true/);
assert.match(recorder,/ensureRecordingCtx\(preservePlayback\)/);
assert.doesNotMatch(recorder,/stopAllTransports\(\)/);
assert.doesNotMatch(recorder,/stopForNavigation/);
assert.match(recorder,/자동 화면 꺼짐은 방지합니다 · 녹음 중에는 직접 잠그지 마세요/);
assert.match(recorder,/function uploadExternalFile\(file\)/);
assert.match(recorder,/function handleRecordDrop\(event\)/);
assert.match(recorder,/recordListCard\.addEventListener\('dragover',handleRecordDragOver\)/);
assert.match(recorder,/recordListCard\.addEventListener\('drop',handleRecordDrop\)/);
assert.match(recorder,/MAX_UPLOAD_BYTES=15\*1024\*1024/);
assert.match(recorder,/MAX_UPLOAD_DURATION_MS=30\*60\*1000/);
assert.match(recorder,/function decodedAudioFileDuration\(file\)/);
assert.match(recorder,/return await mediaElementAudioDuration\(file\)/);
assert.match(recorder,/return await decodedAudioFileDuration\(file\)/);
assert.match(recorder,/MP3 업로드를 위한 저장소 업데이트가 필요합니다 · \$\{SCHEMA_ERROR_CODE\}/);
assert.match(recorder,/const SCHEMA_ERROR_CODE='DB-'\+String\(/);
assert.match(recorder,/sourceType:'upload'/);
assert.match(recorder,/await window\.OliveCloud\.uploadRecording\(uploaded\)/);
assert.doesNotMatch(recorder,/recordBacking|backingAudio|backingPlaying/);
assert.match(recorder,/resumeAfterVisibility/);
assert.match(recorder,/window\.confirm\(`“\$\{row\.title\}” 녹음을 삭제할까요/);
assert.match(recorder,/function recordingListRequestIsCurrent\(userId,token\)/);
assert.match(recorder,/const delays=\[0,250,750\]/);
assert.match(recorder,/if\(!force && recordingListLoadPromise && recordingListLoadUserId===userId\)/);
assert.match(recorder,/녹음 목록을 불러오지 못했습니다 · 연결되면 다시 시도합니다/);
assert.match(recorder,/visibilityState==='visible' && currentUser\) loadRecordings\(\)/);
assert.match(recorder,/window\.addEventListener\('online',[\s\S]*?loadRecordings\(true\)/);

assert.match(audioRuntime,/function ensurePlaybackCtx\(\)/);
assert.match(audioRuntime,/function prepareForegroundPlaybackMode\(\)/);
assert.match(audioRuntime,/__backgroundMediaPaused && hasBackgroundTransportPlaying\(\)[\s\S]*?stopBackgroundTransports\(\)/);
assert.match(audioRuntime,/function beginForegroundPlaybackFromGesture\(\)/);
assert.match(audioRuntime,/return beginPlaybackFromGesture\(prepareForegroundPlaybackMode\(\)\)/);
assert.match(audioRuntime,/recording\?'play-and-record':hasBackgroundTransportPlaying\(\)\?'playback':'ambient'/);
assert.match(audioRuntime,/function ensureBackgroundPlaybackCtx\(label\)/);
assert.match(audioRuntime,/function ensureBackgroundPlaybackCtx\(label\)\{[\s\S]*?stopCompetingBackgroundTransports\(label\)/);
assert.match(audioRuntime,/function resumeBackgroundPlayback\(\)[\s\S]*?await withTimeout\(resumeReady,4500\)[\s\S]*?setBackgroundTransportsPaused\(false\)/);
assert.match(audioRuntime,/let __backgroundMediaActionMode = ''/);
assert.match(audioRuntime,/if\(__backgroundMediaActionMode===actionMode\) return/);
assert.doesNotMatch(audioRuntime,/clearBackgroundTempoActions/);
assert.doesNotMatch(audioRuntime,/function pauseBackgroundPlayback\(\)[\s\S]*?setActionHandler\('seek/);
assert.match(audioRuntime,/navigator\.audioSession\.type = mode/);
assert.match(audioRuntime,/function claimExternalMediaSession\(owner\)/);
assert.match(audioRuntime,/if\(navigator\.mediaSession && !__externalMediaSessionOwner\)/);
assert.match(audioRuntime,/function startBackgroundMedia\(label,preparedCtx\)/);
assert.match(audioRuntime,/function beginPlaybackFromGesture\(preferredMode='playback'\)/);
assert.match(audioRuntime,/function beginPlaybackFromGesture\(preferredMode='playback'\)\{[\s\S]*?recording\?'play-and-record':preferredMode/);
assert.match(audioRuntime,/ctx\.resume\(\)/);
assert.match(audioRuntime,/function stopHiddenUnsafeTransports\(\)/);
assert.match(audioRuntime,/function transportKeepsWhenHidden\(transport\)/);
assert.match(audioRuntime,/!transportKeepsWhenHidden\(transport\)/);
assert.match(audioRuntime,/if\(hasHiddenSafeTransportPlaying\(\)\)/);
assert.match(audioRuntime,/window\.OliveRecorder\.resumeAfterVisibility\(\)/);
assert.match(audioRuntime,/if\(!anySounding\(\) && !recording && !hiddenSafe\)[\s\S]*?setAudioSession\('ambient'\)/);
assert.match(rhythm,/await ensurePlaybackCtx\(\)/);
assert.match(ear,/beginForegroundPlaybackFromGesture\(\)/);
assert.match(ear,/playTone\([^\n]+, ctx\)/);
assert.match(core,/function playTone\([^)]*preparedCtx\)[\s\S]*?preparedCtx \|\| getCtx\(\)/);
for(const source of [metronome,jam]){
  assert.match(source,/await ensureBackgroundPlaybackCtx\(/);
  assert.match(source,/const START_LEAD_TIME ?= ?0\.01/);
}
assert.doesNotMatch(core,/leavingTrainer|stopForNavigation/);
assert.match(core,/enteringTuner[\s\S]*?stopAllTransports\(\)/);
assert.doesNotMatch(appShell,/stopForNavigation/);

assert.match(cloud,/subscribeSession/);
assert.match(cloud,/from\('practice-recordings'\)\.upload/);
assert.match(cloud,/rpc\('reserve_practice_recording'/);
assert.match(cloud,/rpc\('finalize_practice_recording'/);
assert.match(cloud,/createSignedUrls\(recordings\.map\(row=>row\.object_path\),60\*60\)/);
assert.match(cloud,/storage\.from\('practice-recordings'\)\s*\.download/);
assert.match(cloud,/await deleteAllRecordingObjects\(\)/);
assert.match(cloud,/await clearRecordingAudioCache\(userId\)/);

assert.match(recordingCache,/const MAX_ENTRIES=10/);
assert.match(recordingCache,/const MAX_BYTES=50\*1024\*1024/);
assert.match(recordingCache,/root\.indexedDB\.open/);
assert.match(recordingCache,/storage\.persist\(\)/);
assert.match(recorder,/cache\.getMany\(userId,rows\)/);
assert.match(recorder,/findPlaybackBlob\(row\)/);
assert.match(recorder,/await cacheRowBlob\(saved,saved\.blob\)/);
assert.match(recorder,/await cache\.remove\(currentUser\.id,row\.id\)/);

// iOS Safari에서는 검증된 Web Audio 출력을 실제 MediaStream 운반자로 보내고,
// 배속할 때는 별도 처리기로 음높이를 보존한다.
const playRow=recorder.match(/function playRow\(row,requestedOffset\)\{[\s\S]*?\n  \}/)?.[0]||'';
assert.match(playRow,/beginPlaybackFromGesture\(\)/);
assert.match(playRow,/preferPersistentNativePlayback\(\)/);
assert.match(playRow,/stopBackgroundTransports\(\)/);
assert.match(playRow,/startPersistentNativePlayback\(playbackUrl,row,token,offset\)/);
assert.match(playRow,/findPlaybackBlob\(row\)/);
assert.match(playRow,/row\.playback_url/);
assert.match(playRow,/cloudPlayingId===row\.id && seeking/);
assert.match(playRow,/prepareNativeOffset\(offset\)/);
assert.match(playRow,/startNormalizedNative\(playbackUrl,playback,row,token,offset\)/);
assert.doesNotMatch(playRow,/cloudPlaybackMode==='native-paused'/);
assert.match(playRow,/playDecodedBlob\(playback,recordingBlob,row,token/);
assert.match(recorder,/function createExpandedPlayer\(row\)/);
assert.match(recorder,/waveform\.setAttribute\('role','slider'\)/);
assert.match(recorder,/function bindWaveformScrubbing\(waveform,row\)/);
assert.match(recorder,/waveform\.setPointerCapture\(pointerId\)/);
assert.match(recorder,/waveform\.addEventListener\('pointermove'/);
assert.match(recorder,/const edgeSnap=Math\.min\(12,bounds\.width\*\.04\)/);
assert.match(recorder,/const PLAYBACK_RATE_MIN=\.5/);
assert.match(recorder,/const PLAYBACK_RATE_MAX=1\.5/);
assert.match(recorder,/const PLAYBACK_RATE_STEP=\.05/);
assert.match(recorder,/SOUND_TOUCH_PROCESSOR_URL='\.\/vendor\/soundtouch\/soundtouch-processor\.js\?v=195'/);
assert.match(recorder,/function makeCloudTransportAudio\(\)/);
assert.match(recorder,/audio\.dataset\.oliveRecordingTransport='true'/);
assert.match(recorder,/ctx\.createMediaStreamDestination\(\)/);
assert.match(recorder,/function installCloudMediaActions\(actionMode\)/);
assert.match(recorder,/cloudMediaSessionActionMode=installCloudMediaActions\(actionMode\)\?actionMode:''/);
assert.match(recorder,/function refreshCloudMediaSessionPosition\(minInterval=750\)/);
assert.match(recorder,/audio\.addEventListener\('timeupdate',\(\)=>refreshCloudMediaSessionPosition\(750\)\)/);
assert.match(recorder,/cloudMediaPositionUpdatedAt=0;[\s\S]*?refreshCloudMediaSessionPosition\(0\)/);
assert.match(recorder,/setCloudMediaAction\('pause',null\)/);
assert.match(recorder,/function ensureSoundTouchProcessor\(ctx\)/);
assert.match(recorder,/new AudioWorkletNode\(ctx,'soundtouch-processor'/);
assert.match(recorder,/source\.playbackRate\.value=rate/);
assert.match(recorder,/stretch\.parameters&&stretch\.parameters\.get\('playbackRate'\)/);
assert.match(audioRuntime,/if\(!anySounding\(\) && !recording && !hiddenSafe\)/);
assert.match(soundTouchProcessor,/PROCESSOR_NAME = "soundtouch-processor"/);
assert.match(soundTouchProcessor,/registerProcessor\(PROCESSOR_NAME, SoundTouchProcessor\)/);
assert.match(soundTouchLicense,/Mozilla Public License Version 2\.0/);
assert.match(recorder,/audio\.preservesPitch=true/);
assert.match(recorder,/audio\.webkitPreservesPitch=true/);
assert.match(recorder,/source\.loopStart=region\.a/);
assert.match(recorder,/source\.loopEnd=region\.b/);
assert.match(recorder,/record-loop-marker start/);
assert.match(recorder,/record-player-tool icon repeat/);
assert.match(recorder,/rateSlider\.type='range'/);
assert.match(recorder,/function bindPlaybackRateReset\(slider,row\)/);
assert.match(recorder,/slider\.addEventListener\('dblclick',reset\)/);
assert.match(recorder,/switchActivePlaybackToDirect\(row\)/);
assert.match(recorder,/function makeCloudNativeAudio\(\)/);
assert.match(recorder,/audio\.dataset\.oliveRecordingPlayback='true'/);
assert.match(recorder,/function configureCloudMediaSession\(row\)/);
assert.match(recorder,/claimExternalMediaSession\('recording-playback'\)/);
assert.match(recorder,/setCloudMediaAction\('seekbackward'/);
assert.match(recorder,/setCloudMediaAction\('seekforward'/);
assert.match(recorder,/const amount=Number\(details&&details\.seekOffset\)\|\|10/);
assert.match(recorder,/if\(recording \|\| startPending\)[\s\S]*?녹음을 정지한 뒤 목록을 재생해 주세요/);
assert.match(recorder,/if\(cloudPlayingId \|\| cloudMediaId\) stopCloudPlayback\(false\)/);
assert.match(recorder,/audio\.addEventListener\('loadedmetadata',[\s\S]*?syncNativePlaybackSettings/);
assert.match(recorder,/audio\.loop=Boolean\(region\.enabled/);
assert.match(recorder,/async function waveformFromBlob\(blob\)/);
assert.match(recorder,/waveform:compactWaveform\(waveformLevels,WAVEFORM_POINTS\)/);
assert.match(recorder,/playbackGain:playbackGainForRecording\(waveformLevels,recordingPeak\)/);
assert.match(recorder,/gain\.gain\.value=rowPlaybackGain\(row\)/);
assert.match(recorder,/gain\.gain\.value=rowPlaybackGain\(draft\)/);
assert.match(recorder,/const gain=makeMono\(ctx\.createGain\(\)\)/);
assert.match(recorder,/ctx\.createMediaElementSource\(cloudFallbackAudio\)/);
assert.match(recorder,/stopPlayback:stopPlaybackForOtherTool/);
assert.match(recorder,/keepWhenHidden:true/);
assert.match(recorder,/if\(!ctx \|\| ctx\.state==='closed'\) throw new Error\('RecordingContextClosed'\)/);
assert.match(recorder,/saveRecordingWaveform\(row\.id,values\)/);
assert.match(cloud,/p_waveform:Array\.isArray/);
assert.match(cloud,/p_recorded_at:String\(recording&&recording\.recordedAt/);
assert.match(cloud,/p_playback_gain:Number\(recording&&recording\.playbackGain\)/);
assert.match(cloud,/p_source_type:String\(recording&&recording\.sourceType\|\|'recording'\)/);
assert.match(cloud,/ui\.accountViews=\['earCloud','recordCloud'\]/);
assert.match(cloud,/ui\.accountViews\.forEach\(view=>\{/);
assert.match(cloud,/rpc\('save_practice_recording_waveform'/);
assert.match(recorder,/const result=await window\.OliveCloud\.downloadRecording\(row\)/);
assert.match(recorder,/decodeAudioBlob\(ctx,result\.blob\)/);
assert.match(recorder,/ctx\.createBufferSource\(\)/);
assert.match(recorder,/이 녹음 파일을 재생할 수 없습니다 · 다운로드로 확인해 주세요/);
assert.doesNotMatch(recorder,/const cloudAudio=new Audio\(\)/);
for(const source of [metronome,jam]){
  assert.match(source,/function scheduler\(\)\{[\s\S]*?if\(isBackgroundMediaPaused\(\)\)/);
  assert.match(source,/function visualLoop\(gen\)\{[\s\S]*?if\(isBackgroundMediaPaused\(\)\)/);
  assert.match(source,/function setMediaPaused\(paused\)\{[\s\S]*?clearTimeout\(timerID\)/);
  assert.match(source,/setContext:ctx=>\{/);
}

assert.match(migration,/create table if not exists public\.practice_recordings/);
assert.match(migration,/status in \('pending','ready'\)/);
assert.match(migration,/v_count >= 50/);
assert.match(migration,/v_bytes\+p_byte_size > 262144000/);
assert.match(migration,/values \('practice-recordings','practice-recordings',false,15728640\)/);
assert.match(migration,/Users upload reserved recording objects/);
assert.match(migration,/Users read their own recording objects/);
assert.match(migration,/Users delete their own recording objects/);
assert.match(migration,/delete from public\.practice_recordings where user_id=v_user_id/);
assert.match(waveformMigration,/add column if not exists waveform smallint\[\]/);
assert.match(waveformMigration,/create or replace function public\.save_practice_recording_waveform/);
assert.match(waveformMigration,/select 7::integer/);
assert.match(timestampMigration,/p_recorded_at timestamptz/);
assert.match(timestampMigration,/recorded_at\s*\n\s*\) values/);
assert.match(timestampMigration,/select 8::integer/);
assert.match(playbackGainMigration,/add column if not exists playback_gain real/);
assert.match(playbackGainMigration,/p_playback_gain real/);
assert.match(playbackGainMigration,/select 9::integer/);
assert.match(uploadMigration,/add column if not exists source_type text/);
assert.match(uploadMigration,/source_type in \('recording','upload'\)/);
assert.match(uploadMigration,/source_type='upload' and duration_ms between 1000 and 1800000/);
assert.match(uploadMigration,/p_source_type text/);
assert.match(uploadMigration,/select 10::integer/);
assert.match(mimeMigration,/allowed_mime_types=excluded\.allowed_mime_types/);
assert.match(mimeMigration,/select 11::integer/);

assert.match(edge,/from\("practice-recordings"\)/);
assert.match(edge,/\.remove\(recordingPaths\)/);
assert.ok(edge.indexOf('.remove(recordingPaths)')<edge.indexOf('auth.admin.deleteUser(user.id)'),
  'recording objects are removed before the auth user');

console.log('recording feature tests passed');
